name: Deploy Bicep Template and code

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_PACKAGE_PATH: "."
  NODE_VERSION: 14
  ASP_NAME: "asp-${{ github.sha }}"
  WEBAPP_NAME: "webapp-${{ github.sha }}"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1

      - name: Build TypeScript Node.js app
        run: npm install && npm run build

      - name: Deploy App Service Plan and Web App
        uses: Azure/arm-deploy@v1
        with:
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./bicep/main.bicep
          parameters: 'aspName=${{ env.ASP_NAME }} webAppName=${{ env.WEBAPP_NAME }}'

      - name: Deploy code to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: logout
        run: |
          az logout